import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import { Metadata } from "next";
import "@/styles/globals.css";
import { ReactNode } from "react";
import { TeamProvider } from "@/lib/contexts/team";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Toaster richColors position="top-center" />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TeamProvider>{children}</TeamProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
